apiVersion: v1
kind: Service
metadata:
  name: sb-hello-world-svc
  labels:
    app: sb-hello-world
    tier: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sb-hello-world
    tier: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sb-hello-world
  labels:
    app: sb-hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sb-hello-world
        tier: dev
    spec:
      containers:
      - name:  sb-hello-world
        image: gcr.io/kenthua-testing/spring-boot:latest
        env:
        - name: GET_HOSTS_FROM
          value: dns
